# Generated by Django 4.2 on 2025-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                ("size", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("stock", models.PositiveIntegerField(default=1)),
                ("image", models.ImageField(upload_to="products/base/")),
                ("is_available", models.BooleanField(default=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
