# Generated by Django 4.2 on 2025-09-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("text_color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "custom_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="customizations/images/"
                    ),
                ),
                ("placement_data", models.JSONField(blank=True, null=True)),
                (
                    "text_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="customizations/final_previews/",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customizations",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
