# Generated by Django 4.2 on 2025-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customization Setting",
                "verbose_name_plural": "Customization Settings",
            },
        ),
    ]
