# Generated by Django 4.2 on 2025-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customizations", "0002_customizationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customization",
            name="image_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="customization",
            name="text_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
